# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d97f9372e4ed44e8ec8a301efdb6a49c14df435eda0e33453ab3389dafd9aaa96cb0f665235fa83d0add89d01229cddef38f5b81d63c30328cad5132dbb8cf9c

test:
  secret_key_base: 5274fe3bfa5e1664ba249860869dfd73e9853b033cafc8ab0b361129e656a5d03d2515c223f81ac3bcf86878f0a50ff3edea64702a78ab65df8fcae262edd4bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
